apiVersion: solution.sap/v1
kind: Solution

metadata:
  name: hello-world-cee7b
  version: 1.0.2
  description: Simple Hello World AI agent for testing 1

assets:
  - ref: ./assets/hello-world-agent/asset.yaml
